#! /bin/bash

DockerStart() {
    boot2docker up
}

DockerMount() {
    sshfs docker@localhost:/mnt/sda1/Sites ~/Sites -oping_diskarb,volname=b2d-share -p 2022 -o reconnect -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o password_stdin < ~/.boot2docker/b2d-passwd
}

DockerEnd() {
    umount -f ~/Sites
    boot2docker stop
}

### the box must be turned off

# start port
function DockerPort {  
for i in {49000..49900}; do
    VBoxManage modifyvm "boot2docker-vm" --natpf1 "tcp-port$i,tcp,,$i,,$i";
    VBoxManage modifyvm "boot2docker-vm" --natpf1 "udp-port$i,udp,,$i,,$i";
done
}

# remove port
function DockerRmPort {  
for i in {49000..49900}; do
    VBoxManage modifyvm "boot2docker-vm" --natpf1 delete "tcp-port$1";
    VBoxManage modifyvm "boot2docker-vm" --natpf1 delete "udp-port$1";
done
}

